[build]
builder = "dockerfile"

[[services]]
name = "goverde-api"
dockerfilePath = "apps/api/Dockerfile"
healthcheckPath = "/health"

[[services]]
name = "goverde-web"
dockerfilePath = "apps/web/Dockerfile"

[[services]]
name = "goverde-portal"
dockerfilePath = "apps/portal/Dockerfile"
